
# teracy-dev related settings
teracy-dev:
  require_version: ">= 0.6.0-a1-SNAPSHOT"
  extensions: []

# vagrant related settings
vagrant: {}

# default settings for all nodes
default: {}

# specific nodes, each node will override the default
nodes: []
