
# teracy-dev related settings
teracy-dev:
  require_version: ">= 0.6.0-a1-SNAPSHOT"
  extensions:
    - _id: "0"
      path:
        lookup: extensions # we can configure where to lookup for the extension, "extensions" by default if no configured
        extension: teracy-dev-core # extension_path, we'll lookup the extension by its lookup_path + extension_path
      location: # auto download the extension into the lookup_path
        git: https://github.com/hoatle/teracy-dev-core.git
        # ref:
        # tag:
        branch: develop
      require_version: ">= 0.1.0-SNAPSHOT"
      enabled: true # when true, extension will be auto-downloaded if not available yet and will load this extension to be used
    # extension must have manifest.yaml file to describe its name, version and optional description
    # optional: config_default.yaml, teracy-dev-ext.rb will be auto loaded if available

# vagrant related settings
vagrant: {}

# default settings for all nodes
default: {}

# specific nodes, each node will override the default
nodes: []
